### ISSUE TITLE
Recommend a change to how thresholds are set when creating a multisig wallet on TESTNET.

### ISSUE THREAD

**Issue by StrikeAttack** [theQRL/qips#24]
During TESTNET wallet creation, integers are the only values allowed for weights and thresholds. Entering a threshold of 0 successfully creates a wallet.

Nodes do not perform a threshold check on submitted transactions until the first vote is cast, at which point a wallet with a threshold of 0 would execute the transaction after any first vote.

However, from a user perspective, entering a threshold of 0 might be interpreted as zero votes necessary to execute said transaction, and from their a user perspective, as any proposed transaction would have mathematically already met the threshold, might expect a transaction to execture as soon as it is entered.

Granted, I cannot think of a use-case for entering 0 as a threshold for a wallet, but I'm leaning towards removing 0 as a valid value. In addition, 0 is not technically an integer (whole number), it is known as a 'neutral number'.

While this isn't a risk point, it may cause some user confusion.
<img width="889" alt="multisig 0 threshold" src="https://user-images.githubusercontent.com/45234252/76682047-a1c20b00-65c6-11ea-88f1-f4d44d955071.png">

**Comment by StrikeAttack** [comment]
In addition, it seems logical that the threshold should always be <= the lowest signatory value.
<img width="864" alt="20200320 Sig Value of 1 - Two Signaturies With Weights of 2" src="https://user-images.githubusercontent.com/45234252/77212728-45834d80-6ad6-11ea-9df1-f9ed1428f617.png">

**Comment by jplomas** [comment]
Issue for theqrl/qrl-wallet repo
